#!/usr/bin/env node

import { readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

import { assert, isObject, readCategories } from './lib/catalog-entry.mjs'

const scriptRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
export const defaultBase = 'https://deepseek1024.com'
// Must stay aligned with UNCLASSIFIED_CATEGORY in apps/web/worker/lib/categories.ts
// (the website/API label for the same bucket); the .mjs script cannot import Worker TS.
const unclassifiedLabel = { en: 'Unclassified', zh: '待分类' }
const generatedNotice = {
  zh: '<!-- 本文件由 scripts/build-readme.mjs 从 deepseek1024.com 目录 API 自动生成，请勿手工编辑。 -->',
  en: '> This file is generated by `scripts/build-readme.mjs` from the DSH 1024Store catalog API. Do not edit it directly.',
}

function text(value) {
  return typeof value === 'string' ? value.replace(/\s+/g, ' ').trim() : ''
}

function updatedDate(value) {
  const date = typeof value === 'string' ? value.slice(0, 10) : ''
  assert(/^\d{4}-\d{2}-\d{2}$/.test(date), `Registry has an invalid updated timestamp: ${String(value)}`)
  return date
}

function normalizePlugin(plugin, id, stars) {
  assert(isObject(plugin), 'Registry contains an invalid plugin entry')
  const name = text(plugin.name)
  const url = typeof plugin.url === 'string' ? plugin.url : ''
  assert(name.length > 0 && /^https:\/\/github\.com\//.test(url), `Registry plugin ${id} must have a name and GitHub url`)
  return {
    id,
    name,
    owner: text(plugin.owner),
    url,
    category: typeof plugin.category === 'string' && plugin.category.length > 0 ? plugin.category : 'unclassified',
    description: {
      en: text(plugin.description?.en),
      zh: text(plugin.description?.zh),
    },
    added: typeof plugin.added === 'string' ? plugin.added : null,
    stars,
  }
}

export function normalizeRegistry(data) {
  assert(isObject(data) && Array.isArray(data.plugins), 'Registry response must contain a plugins array')
  return {
    updated: updatedDate(data.updated),
    plugins: data.plugins.map(plugin => {
      assert(isObject(plugin) && typeof plugin.id === 'string' && /^[^/]+\/[^/]+$/.test(plugin.id), 'Registry plugins must carry an owner/repository id')
      return normalizePlugin(plugin, plugin.id, Number.isInteger(plugin.stars) ? plugin.stars : null)
    }),
  }
}

export function adaptLegacyRegistry(data) {
  assert(isObject(data) && Array.isArray(data.plugins), 'Legacy /plugins.json must contain a plugins array')
  return {
    updated: updatedDate(data.updated),
    plugins: data.plugins.map(plugin => {
      assert(isObject(plugin) && typeof plugin.url === 'string', 'Legacy plugins must carry a url')
      const derived = new URL(plugin.url).pathname.replace(/^\/+/, '').replace(/\/+$/, '')
      const id = /^[^/]+\/[^/]+$/.test(derived) ? derived : `${plugin.owner}/${plugin.name}`
      return normalizePlugin(plugin, id, null)
    }),
  }
}

function detectRegistryShape(data) {
  const plugins = isObject(data) ? data.plugins : undefined
  const first = Array.isArray(plugins) ? plugins.find(value => isObject(value)) : undefined
  if (first !== undefined && typeof first.id !== 'string') return adaptLegacyRegistry(data)
  return normalizeRegistry(data)
}

export async function loadRegistry(options = {}) {
  if (options.fromFile !== undefined) {
    return detectRegistryShape(JSON.parse(await readFile(options.fromFile, 'utf8')))
  }
  const fetchImplementation = options.fetchImplementation ?? globalThis.fetch
  const base = (options.base ?? defaultBase).replace(/\/+$/, '')
  const registryResponse = await fetchImplementation(`${base}/api/v1/registry`)
  if (registryResponse.ok) {
    return normalizeRegistry(JSON.parse(await registryResponse.text()))
  }
  if (registryResponse.status !== 404) {
    throw new Error(`GET ${base}/api/v1/registry failed: HTTP ${registryResponse.status}`)
  }
  const legacyResponse = await fetchImplementation(`${base}/plugins.json`)
  if (!legacyResponse.ok) {
    throw new Error(`GET ${base}/plugins.json fallback failed: HTTP ${legacyResponse.status}`)
  }
  return adaptLegacyRegistry(JSON.parse(await legacyResponse.text()))
}

function comparePlugins(left, right) {
  const leftName = left.name.toLocaleLowerCase('en-US')
  const rightName = right.name.toLocaleLowerCase('en-US')
  return leftName.localeCompare(rightName, 'en-US')
    || left.name.localeCompare(right.name, 'en-US')
    || left.id.localeCompare(right.id, 'en-US')
}

export function groupPlugins(registry, categories) {
  const ordered = [...categories].sort((left, right) => (left.order ?? 0) - (right.order ?? 0) || String(left.id).localeCompare(String(right.id), 'en-US'))
  const buckets = new Map(ordered.map(category => [category.id, []]))
  const unclassified = []
  for (const plugin of registry.plugins) {
    (buckets.get(plugin.category) ?? unclassified).push(plugin)
  }
  const groups = ordered
    .filter(category => buckets.get(category.id).length > 0)
    .map(category => ({
      id: category.id,
      label: category.label,
      plugins: [...buckets.get(category.id)].sort(comparePlugins),
    }))
  if (unclassified.length > 0) {
    groups.push({ id: 'unclassified', label: unclassifiedLabel, plugins: [...unclassified].sort(comparePlugins) })
  }
  return groups
}

function pluginLine(plugin, locale) {
  const preferred = plugin.description[locale]
  const fallback = locale === 'zh' ? plugin.description.en : plugin.description.zh
  const description = preferred.length > 0 ? preferred : fallback
  return description.length > 0
    ? `- [${plugin.name}](${plugin.url}) — ${description}`
    : `- [${plugin.name}](${plugin.url})`
}

function categoryIndex(groups, locale) {
  return groups.map(group => `- [${group.label[locale]}](#${group.id}) (${group.plugins.length})`).join('\n')
}

function categorySections(groups, locale) {
  return groups.map(group => [
    `<a id="${group.id}"></a>`,
    '',
    `## ${group.label[locale]}`,
    '',
    group.plugins.map(plugin => pluginLine(plugin, locale)).join('\n'),
  ].join('\n')).join('\n\n')
}

function chineseReadme(registry, groups) {
  const total = registry.plugins.length
  return `# DSH 1024Store

${generatedNotice.zh}

面向 [DeepSeek Harness](https://github.com/deepseek-ai/DeepSeek-Harness)（\`dsh\`）生态的社区插件目录，共收录 **${total}** 个插件（含 PR 收录与 GitHub \`dsh-plugin\` topic 自动发现），目录数据更新于 ${registry.updated}。

这里主要展示可安装的插件。每个插件由各自作者独立开发和维护，收录仅表示其通过了目录的基础格式校验。

[在线网站](https://deepseek1024.com/) · [英文目录](catalog/README.md) · [提交插件](CONTRIBUTING.md)

[![GitHub Stars](https://img.shields.io/github/stars/imsai-sh/awesome-deepseek-harness-plugins?style=social)](https://github.com/imsai-sh/awesome-deepseek-harness-plugins/stargazers)

> 如果这个目录帮你找到好用的插件，欢迎点个 [⭐ Star](https://github.com/imsai-sh/awesome-deepseek-harness-plugins/stargazers)，让更多 DeepSeek Harness 用户看到它。

## 安装插件并计入统计

网站优先提供开源包装 CLI；它会调用官方 DeepSeek Harness 插件命令、校验 profile 的真实安装结果，并把匿名安装结果可靠地上报到排行榜：

\`\`\`bash
npx dsh1024 add <owner>/<repository>
\`\`\`

默认安装到 \`web\` profile，可用 \`--profile <name>\` 指定；仓库标识和 \`--profile\` 之外的参数会原样传给官方 CLI；参数可能与包装器冲突时可放到 \`--\` 后，例如 \`... -- --ignore-scripts --reporter append-only\`。透传参数不会写入遥测或本地 receipt。

统计身份是保存在 \`$DSH_HOME/.dsh-1024store/\` 的随机安装实例 ID，不是实名用户或账号。CLI 不上传命令输出、路径、用户名、环境变量、会话内容或原始错误；可用 \`npx dsh1024 telemetry disable\`、\`DO_NOT_TRACK=1\` 或 \`DSH1024_TELEMETRY=0\`（旧变量名 \`DSH_1024STORE_TELEMETRY\` 仍兼容）关闭。直接使用官方 \`dsh plugin\` 命令仍然可用，但不会计入 DSH 1024Store 安装统计。详细字段、口径、存储和部署方式见 [安装统计设计](docs/install-analytics.md)，CLI 源码见 [\`packages/dsh1024\`](packages/dsh1024)。

## 提交插件

### 使用 Agent Skill 提交（推荐）

如果你使用 Codex、Claude Code、Cursor 或其他兼容 Agent Skills 的编程助手，可以安装本仓库提供的提交 Skill：

\`\`\`bash
npx skills add imsai-sh/awesome-deepseek-harness-plugins --skill submit-dsh-plugin -g
\`\`\`

安装后告诉助手：

\`\`\`text
使用 $submit-dsh-plugin 检查并提交我的 DeepSeek Harness 插件。
\`\`\`

该 Skill 会检查插件仓库、生成唯一允许提交的目录 JSON、验证变更范围，并在获得授权后创建 PR。静态审查通过的非草稿 PR 会自动合并；合并后 CI 自动同步目录到网站数据库并刷新本 README，贡献者和维护者都不需要手工更新任何生成文件。查看 [Skill 源码](skills/submit-dsh-plugin/SKILL.md)。

### 手动提交

欢迎把你的 DeepSeek Harness 插件提交到本目录。请阅读 [CONTRIBUTING.md](CONTRIBUTING.md)，通过 PR 提交一个新的结构化插件文件；自动审查将验证提交范围和最基础的 DeepSeek Harness 插件配置，通过后自动合并，并由 CI 自动同步到网站与本 README。

安装命令：\`npx dsh1024 add <owner>/<repository>\`。

## 项目定位

本项目与 [awesome-dsh-plugin](https://github.com/awesome-dsh-plugin/awesome-dsh-plugin) 都服务于 DeepSeek Harness 插件生态。在继承其目录数据与社区整理思路的基础上，本项目重点补充两类能力：

- **自动发现与校验**：定期扫描 GitHub 上带有 \`dsh-plugin\` topic 的仓库，校验 \`package.json\`、\`dsh.bundle\` 及插件补丁路径，并以结构化 JSON 提交、自动审查和自动同步维护目录。
- **在线插件市场**：提供功能较完整的 [deepseek1024.com](https://deepseek1024.com/) 网站，支持搜索、分类筛选、排行榜、插件详情及 GitHub 活跃度数据浏览。

## 项目结构

\`\`\`text
catalog/plugins/    插件提交表单与 curated 元数据（每个插件一个 JSON）
catalog/categories.json  分类定义（唯一分类信源）
skills/             面向贡献者的可安装 Agent Skills
apps/web/src/       React + Vite 前端
apps/web/worker/    Cloudflare Worker API 与数据刷新（唯一读写 D1 的进程）
packages/dsh1024/   dsh1024 npm 包：上报安装统计的包装 CLI + DSH 设置页内插件市场
scripts/            提交审查、目录同步与 README 生成脚本
\`\`\`

线上目录数据的唯一信源是 Cloudflare D1；本 README 与 [catalog/README.md](catalog/README.md) 由 CI 从目录 API 全量生成，职责划分见 [仓库布局](docs/repository-layout.md)。

## 本地运行与部署

需要 Node.js 22+、npm 10+。本地开发：

\`\`\`bash
npm ci
cd apps/web
npx wrangler d1 migrations apply dsh-store-star-history --local
cd ../..
npm run dev
\`\`\`

浏览器访问 <http://127.0.0.1:5173>。如需完整 GitHub 数据，可在 \`apps/web/.dev.vars\` 中配置 \`GITHUB_TOKEN\`；本地接收安装事件还需要一个至少 32 字符的 \`INSTALL_CLIENT_HASH_SECRET\`。

部署到 Cloudflare Workers：

\`\`\`bash
cp apps/web/.env.example apps/web/.dev.vars
# 在 apps/web/.dev.vars 中填写 GITHUB_TOKEN 和 INSTALL_CLIENT_HASH_SECRET
npx wrangler login
npm run build
cd apps/web
npx wrangler d1 migrations apply dsh-store-star-history --remote
npx wrangler deploy --secrets-file .dev.vars
\`\`\`

\`wrangler.jsonc\` 已声明 KV、D1、Durable Object、Cron 定时任务和静态资源配置。生产环境要先执行 \`npm run db:migrate:remote\`，再部署 Worker；完整顺序、GitHub API 限额和费用估算见 [Cloudflare 插件发现运维文档](docs/plugin-discovery.md)，公开 API 见 [API 参考](docs/api.md)。请勿提交 \`.dev.vars\`。

## 致谢

感谢以下项目为本目录提供基础与参考：

- [DeepSeek Harness](https://github.com/deepseek-ai/deepseek-harness)：提供插件系统、\`dsh.bundle\` 规范和插件开发文档。
- [awesome-dsh-plugin](https://github.com/awesome-dsh-plugin/awesome-dsh-plugin)：提供初始插件目录数据和社区目录设计参考。

## 插件分类

${categoryIndex(groups, 'zh')}

${categorySections(groups, 'zh')}

## 免责声明

本项目是社区维护的插件索引。插件由各自作者开发和维护，收录不构成安全、质量或维护状态背书。安装插件会在本机运行第三方代码，请在安装前自行审阅源码和依赖。

## 许可证

本仓库采用分区许可：

- 应用、自动化与构建工具等源代码采用 [MIT License](LICENSE)。
- \`catalog/\` 下的插件目录元数据采用 [CC0-1.0](catalog/LICENSE)。
- 初始目录数据导入自 \`awesome-dsh-plugin\`，来源和导入提交见 [catalog/ATTRIBUTION.md](catalog/ATTRIBUTION.md)。

目录中列出的第三方插件不属于本仓库，其源代码分别遵循各自仓库的许可证。
`
}

function englishReadme(registry, groups) {
  const total = registry.plugins.length
  return `# Awesome DeepSeek Harness Plugins

${generatedNotice.en}

The **DSH 1024Store** community catalog for [DeepSeek Harness](https://github.com/deepseek-ai/DeepSeek-Harness) plugins: **${total}** plugins, updated ${registry.updated}.

[Live website](https://deepseek1024.com/) · [中文目录](../README.md) · [Submit a plugin](../CONTRIBUTING.md)

Install any plugin and count it on the leaderboard with:

\`\`\`bash
npx dsh1024 add <owner>/<repository>
\`\`\`

Merged submissions are synced to the website database and into this file automatically; no manual list editing is involved.

## Categories

${categoryIndex(groups, 'en')}

${categorySections(groups, 'en')}
`
}

export async function buildReadmeFiles(registry, categories) {
  const groups = groupPlugins(registry, categories)
  return {
    'README.md': chineseReadme(registry, groups),
    'catalog/README.md': englishReadme(registry, groups),
  }
}

export function parseArguments(argv) {
  const options = { root: scriptRoot, base: defaultBase, check: false, help: false }
  for (let index = 0; index < argv.length; index += 1) {
    const argument = argv[index]
    const value = () => {
      const next = argv[index + 1]
      if (next === undefined || next.startsWith('--')) throw new Error(`${argument} requires a value`)
      index += 1
      return next
    }
    if (argument === '--base') options.base = value()
    else if (argument === '--from-file') options.fromFile = path.resolve(value())
    else if (argument === '--root') options.root = path.resolve(value())
    else if (argument === '--check') options.check = true
    else if (argument === '--help' || argument === '-h') options.help = true
    else throw new Error(`Unknown argument: ${argument}`)
  }
  return options
}

function usage() {
  return `Usage: npm run readme:build [-- options]

Regenerates README.md (Chinese) and catalog/README.md (English) from the full
DSH 1024Store catalog: GET <base>/api/v1/registry, falling back to the legacy
<base>/plugins.json shape when the v1 endpoint is not deployed yet.

Options:
  --base <url>        Catalog API origin (default: ${defaultBase})
  --from-file <json>  Build from a local registry JSON file instead of the network
  --root <path>       Repository root for categories.json and output files
  --check             Verify the committed files are current; do not write
  --help              Show this help`
}

async function main() {
  const options = parseArguments(process.argv.slice(2))
  if (options.help) {
    console.log(usage())
    return
  }
  const categories = await readCategories(options.root)
  const registry = await loadRegistry(options)
  assert(
    registry.plugins.length > 0,
    'Registry returned 0 plugins; refusing to regenerate README projections from a degenerate snapshot.',
  )
  const files = await buildReadmeFiles(registry, categories)

  if (options.check) {
    const stale = []
    for (const [relative, content] of Object.entries(files)) {
      const existing = await readFile(path.join(options.root, relative), 'utf8').catch(() => '')
      if (existing !== content) stale.push(relative)
    }
    if (stale.length > 0) {
      console.error(`Stale generated files: ${stale.join(', ')}. Run npm run readme:build.`)
      process.exitCode = 1
      return
    }
    console.log('README projections are up to date.')
    return
  }

  for (const [relative, content] of Object.entries(files)) {
    await writeFile(path.join(options.root, relative), content)
    console.log(`Wrote ${relative} (${registry.plugins.length} plugins, updated ${registry.updated})`)
  }
}

if (process.argv[1] !== undefined && pathToFileURL(path.resolve(process.argv[1])).href === import.meta.url) {
  try {
    await main()
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error))
    process.exitCode = 1
  }
}
